enum SCREENS {

    AUTHENTICATION_STACK = 'AUTHENTICATION_STACK',
    REGISTER_DRIVER_STACK = 'REGISTER_DRIVER_STACK',
    MAIN_STACK = 'MAIN_STACK',
    EARNINGS_STACK = 'EARNINGS_STACK',
    ORDERS_STACK = 'ORDERS_STACK',
    BALANCE_STACK = 'BALANCE_STACK',
    SETTINGS_STACK = 'SETTINGS_STACK',


    LANGUAGE_SELECT = 'LANGUAGE_SELECT',
    LOGIN = 'LOGIN',
    ENTER_CODE = 'ENTER_CODE',

    ADD_CAR = 'ADD_CAR',
    ADD_DOCUMENTS = 'ADD_DOCUMENTS',
    REGISTER_DRIVER = 'REGISTER_DRIVER',

    BALANCE = 'BALANCE',
    EARNINGS = 'EARNINGS',
    ORDERS = 'ORDERS',
    PROFILE = 'PROFILE',
    SETTINGS = 'SETTINGS',

    CHAT = 'CHAT',
    MAP = 'MAP',
    TRIP = 'TRIP',

}

export default SCREENS;
